-- MySQL Script generated by MySQL Workbench
-- Thu Oct 31 23:32:04 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema sistema_control_escolar
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sistema_control_escolar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_control_escolar` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `sistema_control_escolar` ;

-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`carreras`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`carreras` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`carreras` (
  `carrera_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `descripcion` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`carrera_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`usuarios` (
  `usuario_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(100) NOT NULL,
  `contrasena` VARCHAR(255) NOT NULL,
  `tipo` ENUM('Administrador', 'Maestro', 'Alumno') NOT NULL,
  `fecha_creacion` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`usuario_id`),
  UNIQUE INDEX `correo` (`correo` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`alumnos` (
  `alumno_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `carrera_id` INT NOT NULL,
  `estado` INT NOT NULL,
  `fecha_nacimiento` TIMESTAMP NOT NULL,
  PRIMARY KEY (`alumno_id`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE,
  INDEX `fk_carrera_id` (`carrera_id` ASC) VISIBLE,
  CONSTRAINT `fk_carrera_id`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `sistema_control_escolar`.`carreras` (`carrera_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_usuario_id`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_control_escolar`.`usuarios` (`usuario_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`maestros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`maestros` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`maestros` (
  `maestro_id` INT NOT NULL AUTO_INCREMENT,
  `usuario_id` INT NOT NULL,
  `grado_estudios` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`maestro_id`),
  UNIQUE INDEX `usuario_id_UNIQUE` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `maestros_ibfk_1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `sistema_control_escolar`.`usuarios` (`usuario_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`materias` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`materias` (
  `materia_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NOT NULL,
  `creditos` INT NOT NULL,
  `carrera_id` INT NOT NULL,
  `semestre` INT NOT NULL,
  PRIMARY KEY (`materia_id`),
  INDEX `materias_ibfk_1` (`carrera_id` ASC) VISIBLE,
  CONSTRAINT `materias_ibfk_1`
    FOREIGN KEY (`carrera_id`)
    REFERENCES `sistema_control_escolar`.`carreras` (`carrera_id`)
    ON DELETE RESTRICT)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`asignaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`asignaciones` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`asignaciones` (
  `asignacion_id` INT NOT NULL AUTO_INCREMENT,
  `maestro_id` INT NULL DEFAULT NULL,
  `materia_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`asignacion_id`),
  INDEX `maestro_id` (`maestro_id` ASC) VISIBLE,
  INDEX `materia_id` (`materia_id` ASC) VISIBLE,
  CONSTRAINT `asignaciones_ibfk_1`
    FOREIGN KEY (`maestro_id`)
    REFERENCES `sistema_control_escolar`.`maestros` (`maestro_id`)
    ON DELETE CASCADE,
  CONSTRAINT `asignaciones_ibfk_2`
    FOREIGN KEY (`materia_id`)
    REFERENCES `sistema_control_escolar`.`materias` (`materia_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`horarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`horarios` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`horarios` (
  `horario_id` INT NOT NULL AUTO_INCREMENT,
  `dia` ENUM('Lunes', 'Martes', 'Mi├®rcoles', 'Jueves', 'Viernes', 'S├íbado') NOT NULL,
  `hora_inicio` TIME NOT NULL,
  `hora_fin` TIME NOT NULL,
  PRIMARY KEY (`horario_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`salones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`salones` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`salones` (
  `salon_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `capacidad` INT NOT NULL,
  PRIMARY KEY (`salon_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`grupos` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`grupos` (
  `grupo_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  `horario_id` INT NOT NULL,
  `salon_id` INT NOT NULL,
  `asignacion_id` INT NOT NULL,
  PRIMARY KEY (`grupo_id`),
  INDEX `fk_asignacion_id_idx` (`asignacion_id` ASC) VISIBLE,
  INDEX `grupos_ibfk_3` (`horario_id` ASC) VISIBLE,
  INDEX `grupos_ibfk_4` (`salon_id` ASC) VISIBLE,
  CONSTRAINT `fk_asignacion_id`
    FOREIGN KEY (`asignacion_id`)
    REFERENCES `sistema_control_escolar`.`asignaciones` (`asignacion_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `grupos_ibfk_3`
    FOREIGN KEY (`horario_id`)
    REFERENCES `sistema_control_escolar`.`horarios` (`horario_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `grupos_ibfk_4`
    FOREIGN KEY (`salon_id`)
    REFERENCES `sistema_control_escolar`.`salones` (`salon_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_control_escolar`.`inscripciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `sistema_control_escolar`.`inscripciones` ;

CREATE TABLE IF NOT EXISTS `sistema_control_escolar`.`inscripciones` (
  `inscripcion_id` INT NOT NULL AUTO_INCREMENT,
  `alumno_id` INT NOT NULL,
  `grupo_id` INT NOT NULL,
  `fecha_inscripcion` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`inscripcion_id`),
  INDEX `inscripciones_ibfk_1` (`alumno_id` ASC) VISIBLE,
  INDEX `inscripciones_ibfk_2` (`grupo_id` ASC) VISIBLE,
  CONSTRAINT `inscripciones_ibfk_1`
    FOREIGN KEY (`alumno_id`)
    REFERENCES `sistema_control_escolar`.`alumnos` (`alumno_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `inscripciones_ibfk_2`
    FOREIGN KEY (`grupo_id`)
    REFERENCES `sistema_control_escolar`.`grupos` (`grupo_id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
